# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_redesign_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(1080, 720))
        self.tabWidget.setObjectName("tabWidget")
        self.tabDashboard = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabDashboard.sizePolicy().hasHeightForWidth())
        self.tabDashboard.setSizePolicy(sizePolicy)
        self.tabDashboard.setMinimumSize(QtCore.QSize(1080, 0))
        self.tabDashboard.setObjectName("tabDashboard")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabDashboard)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftHandSide = QtWidgets.QVBoxLayout()
        self.leftHandSide.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftHandSide.setSpacing(6)
        self.leftHandSide.setObjectName("leftHandSide")
        self.inputBox = QtWidgets.QGroupBox(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputBox.sizePolicy().hasHeightForWidth())
        self.inputBox.setSizePolicy(sizePolicy)
        self.inputBox.setMinimumSize(QtCore.QSize(0, 0))
        self.inputBox.setObjectName("inputBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.inputNZeroLabel = QtWidgets.QLabel(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNZeroLabel.sizePolicy().hasHeightForWidth())
        self.inputNZeroLabel.setSizePolicy(sizePolicy)
        self.inputNZeroLabel.setToolTip("")
        self.inputNZeroLabel.setObjectName("inputNZeroLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputNZeroLabel)
        self.inputHalfLifeLabel = QtWidgets.QLabel(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHalfLifeLabel.sizePolicy().hasHeightForWidth())
        self.inputHalfLifeLabel.setSizePolicy(sizePolicy)
        self.inputHalfLifeLabel.setToolTip("")
        self.inputHalfLifeLabel.setObjectName("inputHalfLifeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.inputHalfLifeLabel)
        self.inputTimeScaleLabel = QtWidgets.QLabel(self.inputBox)
        self.inputTimeScaleLabel.setObjectName("inputTimeScaleLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.inputTimeScaleLabel)
        self.inputTimeScaleComboBox = QtWidgets.QComboBox(self.inputBox)
        self.inputTimeScaleComboBox.setObjectName("inputTimeScaleComboBox")
        self.inputTimeScaleComboBox.addItem("")
        self.inputTimeScaleComboBox.addItem("")
        self.inputTimeScaleComboBox.addItem("")
        self.inputTimeScaleComboBox.addItem("")
        self.inputTimeScaleComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputTimeScaleComboBox)
        self.inputNZeroDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNZeroDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.inputNZeroDoubleSpinBox.setSizePolicy(sizePolicy)
        self.inputNZeroDoubleSpinBox.setMaximum(10000000000000.0)
        self.inputNZeroDoubleSpinBox.setObjectName("inputNZeroDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputNZeroDoubleSpinBox)
        self.inputHalfLifeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHalfLifeDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.inputHalfLifeDoubleSpinBox.setSizePolicy(sizePolicy)
        self.inputHalfLifeDoubleSpinBox.setToolTip("")
        self.inputHalfLifeDoubleSpinBox.setMaximum(10000000000000.0)
        self.inputHalfLifeDoubleSpinBox.setObjectName("inputHalfLifeDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inputHalfLifeDoubleSpinBox)
        self.inputNZeroUnitLabel = QtWidgets.QLabel(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNZeroUnitLabel.sizePolicy().hasHeightForWidth())
        self.inputNZeroUnitLabel.setSizePolicy(sizePolicy)
        self.inputNZeroUnitLabel.setObjectName("inputNZeroUnitLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.inputNZeroUnitLabel)
        self.inputNZeroLineEdit = QtWidgets.QLineEdit(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNZeroLineEdit.sizePolicy().hasHeightForWidth())
        self.inputNZeroLineEdit.setSizePolicy(sizePolicy)
        self.inputNZeroLineEdit.setObjectName("inputNZeroLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputNZeroLineEdit)
        self.inputPresetsLabel = QtWidgets.QLabel(self.inputBox)
        self.inputPresetsLabel.setObjectName("inputPresetsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inputPresetsLabel)
        self.inputPresetsComboBox = QtWidgets.QComboBox(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPresetsComboBox.sizePolicy().hasHeightForWidth())
        self.inputPresetsComboBox.setSizePolicy(sizePolicy)
        self.inputPresetsComboBox.setObjectName("inputPresetsComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputPresetsComboBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inputRealTimeLabel = QtWidgets.QLabel(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRealTimeLabel.sizePolicy().hasHeightForWidth())
        self.inputRealTimeLabel.setSizePolicy(sizePolicy)
        self.inputRealTimeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputRealTimeLabel.setObjectName("inputRealTimeLabel")
        self.horizontalLayout_3.addWidget(self.inputRealTimeLabel)
        self.inputSimulatedTimeSpinBox = QtWidgets.QSpinBox(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSimulatedTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.inputSimulatedTimeSpinBox.setSizePolicy(sizePolicy)
        self.inputSimulatedTimeSpinBox.setMaximum(999999999)
        self.inputSimulatedTimeSpinBox.setObjectName("inputSimulatedTimeSpinBox")
        self.horizontalLayout_3.addWidget(self.inputSimulatedTimeSpinBox)
        self.inputSimulatedTimeLabel = QtWidgets.QLabel(self.inputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSimulatedTimeLabel.sizePolicy().hasHeightForWidth())
        self.inputSimulatedTimeLabel.setSizePolicy(sizePolicy)
        self.inputSimulatedTimeLabel.setObjectName("inputSimulatedTimeLabel")
        self.horizontalLayout_3.addWidget(self.inputSimulatedTimeLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.leftHandSide.addWidget(self.inputBox)
        self.controlsBox = QtWidgets.QGroupBox(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsBox.sizePolicy().hasHeightForWidth())
        self.controlsBox.setSizePolicy(sizePolicy)
        self.controlsBox.setMinimumSize(QtCore.QSize(0, 0))
        self.controlsBox.setObjectName("controlsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlsBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlsStartStopButton = QtWidgets.QPushButton(self.controlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsStartStopButton.sizePolicy().hasHeightForWidth())
        self.controlsStartStopButton.setSizePolicy(sizePolicy)
        self.controlsStartStopButton.setObjectName("controlsStartStopButton")
        self.verticalLayout.addWidget(self.controlsStartStopButton)
        self.controlsSimulationSpeedLabel = QtWidgets.QLabel(self.controlsBox)
        self.controlsSimulationSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlsSimulationSpeedLabel.setObjectName("controlsSimulationSpeedLabel")
        self.verticalLayout.addWidget(self.controlsSimulationSpeedLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlsSimSpeedButton_1 = QtWidgets.QPushButton(self.controlsBox)
        self.controlsSimSpeedButton_1.setObjectName("controlsSimSpeedButton_1")
        self.horizontalLayout_2.addWidget(self.controlsSimSpeedButton_1)
        self.controlsSimSpeedButton_2 = QtWidgets.QPushButton(self.controlsBox)
        self.controlsSimSpeedButton_2.setObjectName("controlsSimSpeedButton_2")
        self.horizontalLayout_2.addWidget(self.controlsSimSpeedButton_2)
        self.controlsSimSpeedButton_3 = QtWidgets.QPushButton(self.controlsBox)
        self.controlsSimSpeedButton_3.setObjectName("controlsSimSpeedButton_3")
        self.horizontalLayout_2.addWidget(self.controlsSimSpeedButton_3)
        self.controlsSimSpeedButton_4 = QtWidgets.QPushButton(self.controlsBox)
        self.controlsSimSpeedButton_4.setObjectName("controlsSimSpeedButton_4")
        self.horizontalLayout_2.addWidget(self.controlsSimSpeedButton_4)
        self.controlsSimSpeedButton_5 = QtWidgets.QPushButton(self.controlsBox)
        self.controlsSimSpeedButton_5.setObjectName("controlsSimSpeedButton_5")
        self.horizontalLayout_2.addWidget(self.controlsSimSpeedButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.controlsResetButton = QtWidgets.QPushButton(self.controlsBox)
        self.controlsResetButton.setAutoRepeatDelay(300)
        self.controlsResetButton.setFlat(False)
        self.controlsResetButton.setObjectName("controlsResetButton")
        self.verticalLayout.addWidget(self.controlsResetButton)
        self.leftHandSide.addWidget(self.controlsBox)
        self.statsBox = QtWidgets.QGroupBox(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBox.sizePolicy().hasHeightForWidth())
        self.statsBox.setSizePolicy(sizePolicy)
        self.statsBox.setMinimumSize(QtCore.QSize(0, 0))
        self.statsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsBox.setObjectName("statsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.statsBox)
        self.gridLayout.setObjectName("gridLayout")
        self.statsYAxisLabelStatUnit = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsYAxisLabelStatUnit.sizePolicy().hasHeightForWidth())
        self.statsYAxisLabelStatUnit.setSizePolicy(sizePolicy)
        self.statsYAxisLabelStatUnit.setObjectName("statsYAxisLabelStatUnit")
        self.gridLayout.addWidget(self.statsYAxisLabelStatUnit, 0, 2, 1, 1)
        self.linerow2 = QtWidgets.QFrame(self.statsBox)
        self.linerow2.setFrameShape(QtWidgets.QFrame.VLine)
        self.linerow2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linerow2.setObjectName("linerow2")
        self.gridLayout.addWidget(self.linerow2, 1, 4, 1, 1)
        self.statsRealTimeLabel = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsRealTimeLabel.sizePolicy().hasHeightForWidth())
        self.statsRealTimeLabel.setSizePolicy(sizePolicy)
        self.statsRealTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsRealTimeLabel.setObjectName("statsRealTimeLabel")
        self.gridLayout.addWidget(self.statsRealTimeLabel, 1, 0, 1, 1)
        self.linerow1 = QtWidgets.QFrame(self.statsBox)
        self.linerow1.setFrameShape(QtWidgets.QFrame.VLine)
        self.linerow1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linerow1.setObjectName("linerow1")
        self.gridLayout.addWidget(self.linerow1, 0, 4, 1, 1)
        self.statsRealTimeStatUnit = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsRealTimeStatUnit.sizePolicy().hasHeightForWidth())
        self.statsRealTimeStatUnit.setSizePolicy(sizePolicy)
        self.statsRealTimeStatUnit.setObjectName("statsRealTimeStatUnit")
        self.gridLayout.addWidget(self.statsRealTimeStatUnit, 1, 2, 1, 1)
        self.statsSimulatedTimeLabel = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsSimulatedTimeLabel.sizePolicy().hasHeightForWidth())
        self.statsSimulatedTimeLabel.setSizePolicy(sizePolicy)
        self.statsSimulatedTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsSimulatedTimeLabel.setObjectName("statsSimulatedTimeLabel")
        self.gridLayout.addWidget(self.statsSimulatedTimeLabel, 1, 6, 1, 1)
        self.statsXAxisLabelStatUnit = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsXAxisLabelStatUnit.sizePolicy().hasHeightForWidth())
        self.statsXAxisLabelStatUnit.setSizePolicy(sizePolicy)
        self.statsXAxisLabelStatUnit.setObjectName("statsXAxisLabelStatUnit")
        self.gridLayout.addWidget(self.statsXAxisLabelStatUnit, 0, 9, 1, 1)
        self.statsYAxisLabel = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsYAxisLabel.sizePolicy().hasHeightForWidth())
        self.statsYAxisLabel.setSizePolicy(sizePolicy)
        self.statsYAxisLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsYAxisLabel.setObjectName("statsYAxisLabel")
        self.gridLayout.addWidget(self.statsYAxisLabel, 0, 0, 1, 1)
        self.statsYAxisLabelStat = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsYAxisLabelStat.sizePolicy().hasHeightForWidth())
        self.statsYAxisLabelStat.setSizePolicy(sizePolicy)
        self.statsYAxisLabelStat.setObjectName("statsYAxisLabelStat")
        self.gridLayout.addWidget(self.statsYAxisLabelStat, 0, 1, 1, 1)
        self.statsXAxisLabel = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsXAxisLabel.sizePolicy().hasHeightForWidth())
        self.statsXAxisLabel.setSizePolicy(sizePolicy)
        self.statsXAxisLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsXAxisLabel.setObjectName("statsXAxisLabel")
        self.gridLayout.addWidget(self.statsXAxisLabel, 0, 6, 1, 1)
        self.statsRealTimeStat = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsRealTimeStat.sizePolicy().hasHeightForWidth())
        self.statsRealTimeStat.setSizePolicy(sizePolicy)
        self.statsRealTimeStat.setObjectName("statsRealTimeStat")
        self.gridLayout.addWidget(self.statsRealTimeStat, 1, 1, 1, 1)
        self.statsSimulatedTimeStat = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsSimulatedTimeStat.sizePolicy().hasHeightForWidth())
        self.statsSimulatedTimeStat.setSizePolicy(sizePolicy)
        self.statsSimulatedTimeStat.setObjectName("statsSimulatedTimeStat")
        self.gridLayout.addWidget(self.statsSimulatedTimeStat, 1, 7, 1, 1)
        self.statsXAxisLabelStat = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsXAxisLabelStat.sizePolicy().hasHeightForWidth())
        self.statsXAxisLabelStat.setSizePolicy(sizePolicy)
        self.statsXAxisLabelStat.setObjectName("statsXAxisLabelStat")
        self.gridLayout.addWidget(self.statsXAxisLabelStat, 0, 7, 1, 1)
        self.statsSimulatedTimeStatUnit = QtWidgets.QLabel(self.statsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsSimulatedTimeStatUnit.sizePolicy().hasHeightForWidth())
        self.statsSimulatedTimeStatUnit.setSizePolicy(sizePolicy)
        self.statsSimulatedTimeStatUnit.setObjectName("statsSimulatedTimeStatUnit")
        self.gridLayout.addWidget(self.statsSimulatedTimeStatUnit, 1, 9, 1, 1)
        self.leftHandSide.addWidget(self.statsBox)
        self.horizontalLayout.addLayout(self.leftHandSide)
        self.lineDivider = QtWidgets.QFrame(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDivider.sizePolicy().hasHeightForWidth())
        self.lineDivider.setSizePolicy(sizePolicy)
        self.lineDivider.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineDivider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineDivider.setObjectName("lineDivider")
        self.horizontalLayout.addWidget(self.lineDivider)
        self.verticalGraphVis = QtWidgets.QVBoxLayout()
        self.verticalGraphVis.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalGraphVis.setContentsMargins(5, 5, 5, 5)
        self.verticalGraphVis.setObjectName("verticalGraphVis")
        self.graphWidgetHalfLifeDashboard = PlotWidget(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidgetHalfLifeDashboard.sizePolicy().hasHeightForWidth())
        self.graphWidgetHalfLifeDashboard.setSizePolicy(sizePolicy)
        self.graphWidgetHalfLifeDashboard.setMinimumSize(QtCore.QSize(608, 330))
        self.graphWidgetHalfLifeDashboard.setMaximumSize(QtCore.QSize(608, 330))
        self.graphWidgetHalfLifeDashboard.setObjectName("graphWidgetHalfLifeDashboard")
        self.verticalGraphVis.addWidget(self.graphWidgetHalfLifeDashboard)
        self.labelVis = QtWidgets.QLabel(self.tabDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVis.sizePolicy().hasHeightForWidth())
        self.labelVis.setSizePolicy(sizePolicy)
        self.labelVis.setMinimumSize(QtCore.QSize(608, 330))
        self.labelVis.setMaximumSize(QtCore.QSize(608, 330))
        self.labelVis.setFrameShape(QtWidgets.QFrame.Box)
        self.labelVis.setLineWidth(2)
        self.labelVis.setText("")
        self.labelVis.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVis.setObjectName("labelVis")
        self.verticalGraphVis.addWidget(self.labelVis)
        self.horizontalLayout.addLayout(self.verticalGraphVis)
        self.tabWidget.addTab(self.tabDashboard, "")
        self.tabGraph = QtWidgets.QWidget()
        self.tabGraph.setObjectName("tabGraph")
        self.graphWidgetHalfLife = PlotWidget(self.tabGraph)
        self.graphWidgetHalfLife.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.graphWidgetHalfLife.setObjectName("graphWidgetHalfLife")
        self.tabWidget.addTab(self.tabGraph, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Half Life Vis"))
        self.inputBox.setTitle(_translate("MainWindow", "Input"))
        self.inputNZeroLabel.setText(_translate("MainWindow", "N<sub>0</sub>"))
        self.inputHalfLifeLabel.setText(_translate("MainWindow", "Half Life t(1/2)"))
        self.inputTimeScaleLabel.setText(_translate("MainWindow", "Time Scale"))
        self.inputTimeScaleComboBox.setToolTip(_translate("MainWindow", "Unit of time of half life"))
        self.inputTimeScaleComboBox.setItemText(0, _translate("MainWindow", "Seconds"))
        self.inputTimeScaleComboBox.setItemText(1, _translate("MainWindow", "Minutes"))
        self.inputTimeScaleComboBox.setItemText(2, _translate("MainWindow", "Days"))
        self.inputTimeScaleComboBox.setItemText(3, _translate("MainWindow", "Months"))
        self.inputTimeScaleComboBox.setItemText(4, _translate("MainWindow", "Years"))
        self.inputNZeroDoubleSpinBox.setToolTip(_translate("MainWindow", "Initial Amount"))
        self.inputNZeroUnitLabel.setText(_translate("MainWindow", "N<sub>0</sub> Unit"))
        self.inputNZeroLineEdit.setToolTip(_translate("MainWindow", "Unit of decaying substance (ex. litres, kg)"))
        self.inputNZeroLineEdit.setText(_translate("MainWindow", "Nuclei"))
        self.inputPresetsLabel.setText(_translate("MainWindow", "Presets (optional)"))
        self.inputRealTimeLabel.setText(_translate("MainWindow", "1 Second ="))
        self.inputSimulatedTimeSpinBox.setToolTip(_translate("MainWindow", "How much simulated time passes per real-life second"))
        self.inputSimulatedTimeLabel.setText(_translate("MainWindow", "Simulated Years"))
        self.controlsBox.setTitle(_translate("MainWindow", "Controls"))
        self.controlsStartStopButton.setToolTip(_translate("MainWindow", "Start the simulation according to input"))
        self.controlsStartStopButton.setText(_translate("MainWindow", "Start"))
        self.controlsSimulationSpeedLabel.setText(_translate("MainWindow", "Simulation Speed"))
        self.controlsSimSpeedButton_1.setText(_translate("MainWindow", "0.25x"))
        self.controlsSimSpeedButton_2.setText(_translate("MainWindow", "0.5x"))
        self.controlsSimSpeedButton_3.setText(_translate("MainWindow", "Normal"))
        self.controlsSimSpeedButton_4.setText(_translate("MainWindow", "2x"))
        self.controlsSimSpeedButton_5.setText(_translate("MainWindow", "5x"))
        self.controlsResetButton.setToolTip(_translate("MainWindow", "Completely resets the simulator. If simulation is running, stops it."))
        self.controlsResetButton.setText(_translate("MainWindow", "Full Reset"))
        self.statsBox.setTitle(_translate("MainWindow", "Stats"))
        self.statsYAxisLabelStatUnit.setText(_translate("MainWindow", "Nuclei"))
        self.statsRealTimeLabel.setText(_translate("MainWindow", "Real Time Elapsed:"))
        self.statsRealTimeStatUnit.setText(_translate("MainWindow", "Seconds"))
        self.statsSimulatedTimeLabel.setText(_translate("MainWindow", "Simulated Time Elapsed:"))
        self.statsXAxisLabelStatUnit.setText(_translate("MainWindow", "Years"))
        self.statsYAxisLabel.setText(_translate("MainWindow", "Y Axis:"))
        self.statsYAxisLabelStat.setText(_translate("MainWindow", "__"))
        self.statsXAxisLabel.setText(_translate("MainWindow", "X Axis"))
        self.statsRealTimeStat.setText(_translate("MainWindow", "__"))
        self.statsSimulatedTimeStat.setText(_translate("MainWindow", "__"))
        self.statsXAxisLabelStat.setText(_translate("MainWindow", "__"))
        self.statsSimulatedTimeStatUnit.setText(_translate("MainWindow", "Years"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDashboard), _translate("MainWindow", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraph), _translate("MainWindow", "Graph"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

